<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirm_password</name>
   <tag></tag>
   <elementGuidId>f7183f98-414a-4182-976f-05f8f95f2de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='confirm_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;confirm_password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;تأكيد كلمة المرور&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9853c183-84fa-4194-a327-d51308074adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>92d0be8b-9cb4-4e72-8cfe-a9b7eb3cebbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_password</value>
      <webElementGuid>12ded3e1-71de-4be8-8106-0f1d7bea3019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control auth-form-input valid</value>
      <webElementGuid>f5bd19c8-0ec6-4680-b70a-aa271f467c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>تأكيد كلمة المرور</value>
      <webElementGuid>ac59ca8e-8799-45c0-94a5-bb3634d25406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e9ded5da-a48f-4b74-8c11-34139906930a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>59e33e6e-7644-40e6-8d47-8f0c03f8b614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12568771-83de-4690-b623-90e578addd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_validate&quot;)/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control auth-form-input valid&quot;]</value>
      <webElementGuid>217ccbe4-e016-4bac-b67b-e50c870d032a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='confirm_password']</value>
      <webElementGuid>e835b1dc-3b08-462b-bb76-68db2b27c8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_validate']/div[8]/input</value>
      <webElementGuid>c6e32cf8-27f0-4993-b227-5bae9d8bbc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>3ebc1ac5-d140-41fc-bd8b-fc8b2866ac67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_password' and @placeholder = 'تأكيد كلمة المرور']</value>
      <webElementGuid>1234d311-c8b9-4b83-b7ce-10612cea2a70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
