<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_DetailPrice</name>
   <tag></tag>
   <elementGuidId>b6108017-f2b5-4d53-9492-b68aa16bbff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong.lbl-price</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
