<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_DetailTitle</name>
   <tag></tag>
   <elementGuidId>6f7522e1-fff4-4251-95a7-e853250c3a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.product-title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
