<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_ArticleTitle</name>
   <tag></tag>
   <elementGuidId>293abf40-0800-43fe-bcfc-280a90f9e7a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7c8e110a-f00d-472d-8c38-05413add33fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
